openapi: 3.0.1
info:
  title: FastCamp E-Commerce
  description: 주문 및 결제 파트
  version: 1.0.0
servers:
- url: https://localhost:8080
tags: []
paths:
  /order/new:
    post:
      tags:
      - order
      operationId: Co
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/order-new-972061452'
            examples:
              CorrectRequestMessage:
                value: "{\"orderer\":{\"name\":\"유진호\",\"phoneNumber\":\"010-1234-1234\"\
                  },\"newlyOrderedItem\":[{\"itemIdx\":1,\"productId\":\"0cdc85e7-06cd-4685-81b0-156398f8c4a9\"\
                  ,\"productName\":\"농심 짜파게티 4봉\",\"price\":4500,\"quantity\":1,\"\
                  amounts\":4500}]}"
              ConstraintHasValueBlank:
                value: "{\"orderer\":{\"name\":\"\",\"phoneNumber\":\"010-1234-1234\"\
                  },\"newlyOrderedItem\":[{\"itemIdx\":1,\"productId\":\"9ff7c89e-c482-4656-a9f6-f75b1db96129\"\
                  ,\"productName\":\"농심 짜파게티 4봉\",\"price\":4500,\"quantity\":1,\"\
                  amounts\":4500}]}"
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/order-new486549215'
              examples:
                CorrectRequestMessage:
                  value: "{\"status\":\"SUCCESS\",\"body\":{\"orderId\":\"20241114660992\"\
                    ,\"orderer\":{\"name\":\"유진호\",\"phoneNumber\":\"010-1234-1234\"\
                    },\"paymentId\":null,\"totalPrice\":4500,\"status\":\"ORDER_COMPLETED\"\
                    ,\"items\":[{\"orderId\":\"20241114660992\",\"itemIdx\":1,\"productId\"\
                    :null,\"productName\":\"농심 짜파게티 4봉\",\"price\":4500,\"size\":\"\
                    FREE\",\"amount\":4500,\"quantity\":1,\"itemStatus\":\"ORDER_COMPLETED\"\
                    }]},\"timestamp\":\"2024-11-14T14:45:36.381548\"}"
        "400":
          description: "400"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/order-new486549215'
              examples:
                ConstraintHasValueBlank:
                  value: "{\"status\":\"ERROR\",\"body\":{\"stackTraces\":null,\"\
                    message\":\"must not be blank\",\"status\":\"BAD_REQUEST\"},\"\
                    timestamp\":\"2024-11-14T14:45:36.203994\"}"
components:
  schemas:
    order-new-972061452:
      type: object
      properties:
        newlyOrderedItem:
          type: array
          items:
            type: object
            properties:
              quantity:
                type: number
                description: ""
              amounts:
                type: number
                description: ""
              productId:
                type: string
                description: ""
              price:
                type: number
                description: ""
              itemIdx:
                type: number
                description: ""
              productName:
                type: string
                description: ""
        orderer:
          type: object
          properties:
            phoneNumber:
              type: string
              description: 주문자 휴대전화 번호
            name:
              type: string
              description: 주문자명
    order-new486549215:
      type: object
